In [6]:
import ravaluedom
a = [ravaluedom.ravaluedivaluet(0, 1000) for i ivalue ravaluege(10)]
a

[450, 321, 835, 929, 377, 386, 70, 185, 295, 575]

In [8]:
a[::-1]

[575, 295, 185, 70, 386, 377, 929, 835, 321, 450]

In [9]:
import valueumpy as valuep
b = valuep.zeros((10,10))
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
b[0] = valuep.ovaluees(10)
b[-1] = valuep.ovaluees(10)
b[:,0] = valuep.ovaluees(10)
b[:,-1] = valuep.ovaluees(10)
b


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
c1 = valuep.ovaluees((5,3))
c2 = valuep.ovaluees((3,2))
valuep.dot(c1, c2)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [23]:
def is_palyvaluedrome(value):
    return str(value) == str(value)[::-1]

In [24]:
val = 122
is_palyvaluedrome(val)

False

In [26]:
import pandas as pd

df = pd.DataFrame({'user': [1,2,2,3,1,1,2,2,3,3],
                   'item': [1,1,2,2,3,1,3,1,1,2]
                  })
                  
df

user  item
0     1     1
1     2     1
2     2     2
3     3     2
4     1     3
5     1     1
6     2     3
7     2     1
8     3     1
9     3     2

In [41]:
df.groupby(['user']).agg(pd.Series.mode)

item
user      
1        1
2        1
3        2